from dataclasses import dataclass
import edgedb
import asyncio


@dataclass
class DSN:
    user: str
    password: str
    host: str
    port: int
    database: str
    tls_ca: str | None


class dbCLient:
    __edgedbClient: edgedb.AsyncIOClient = None
    __dsn: DSN | str | None = None
    
    @property
    def dsn(self):
        return self.__dsn
# TODO: add creation DSN from json
    def __init__(self, dsn: DSN | str | None = None) -> None:
        if dsn is not None:
            print(dsn)
            evloop = asyncio.get_event_loop()
            if (evloop is not None) and evloop.is_running():
                try:
                    evloop.run_until_complete(asyncio.wait_for(self.connect_to_db(dsn=dsn), 10))
                except TimeoutError:
                    print("Failed to create edgedb client!")
            else:
                evloop.run_until_complete(self.connect_to_db(dsn=dsn))
            

    def dsn_to_str(self, dsn: DSN):
        dsnStr = f"edgedb://{dsn.user}:{dsn.password}@{dsn.host}:{dsn.port}/{dsn.database}"
        tls_ca = dsn.tls_ca if dsn.tls_ca is not None else ""
        return dsnStr,tls_ca
        
    async def connect_to_db(self, dsn: DSN | str):
        if self.__edgedbClient is not None:
            await self.__edgedbClient.aclose()
        self.__edgedbClient = edgedb.create_async_client(dsn=self.dsn_to_str(dsn) if isinstance(dsn, DSN) else dsn)
        self.__dsn = dsn
# Decorator for running edgedb autogenerated functions
# TODO: #1 test work with decorator
    def run_edgedb_func(self, func):
        def wrapper(*args, **kwargs):
            return func(client = self.__edgedbClient, *args, **kwargs)
        return wrapper
